In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [ ]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [ ]:
x = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [ ]:
x_min = x.min()
x_max = x.max()
x_scaled = (x - x_min) / (x_max - x_min + 1e-8)

In [ ]:
x_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [ ]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.33, random_state=42 , stratify=y)

In [ ]:
model = keras.Sequential([
    layers.Input(shape= (x_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [ ]:
model.compile(
    optimizer='sgd',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history = model.fit(
    x_train.values,y_train.values,
    validation_data = (x_test.values , y_test.values),
    epochs =  100 , batch_size = 4 , verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 191ms/step - accuracy: 0.3000 - loss: 8.8263 - val_accuracy: 0.5000 - val_loss: 3.9313
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.3000 - loss: 5.1509 - val_accuracy: 0.5000 - val_loss: 1.0294
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.1000 - loss: 5.0071 - val_accuracy: 0.6667 - val_loss: 0.8903
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 1.3875 - val_accuracy: 0.5000 - val_loss: 2.0593
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5000 - loss: 1.6062 - val_accuracy: 0.3333 - val_loss: 0.9471
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6000 - loss: 1.3324 - val_accuracy: 0.6667 - val_loss: 0.8783
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 1.1352 - val_accuracy: 0.5000 - val_loss: 4.0289
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.3000 - loss: 3.3882 - val_accuracy: 0.3333 - val_loss: 0.8965
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8000 - loss: 0.5919 - val_accuracy: 0.3333 - val_loss: 1.2256
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.3000 - loss: 2.4550 - val_accuracy: 0.6667 - val_loss: 0.8441
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7180 - val_accuracy: 0.5000 - val_loss: 2.9101
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 1.7959 - val_accuracy: 0.6667 - val_loss: 0.8789
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 1.1700 - val_accuracy: 0.5000 - val_loss: 0.9549
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7765 - val_accuracy: 0.3333 - val_loss: 0.8305
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7069 - val_accuracy: 0.5000 - val_loss: 1.1563
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.3000 - loss: 1.8719 - val_accuracy: 0.3333 - val_loss: 0.8330
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7000 - loss: 0.6357 - val_accuracy: 0.6667 - val_loss: 0.8435
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6631 - val_accuracy: 0.6667 - val_loss: 0.8074
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6866 - val_accuracy: 0.5000 - val_loss: 1.1674
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.8840 - val_accuracy: 0.5000 - val_loss: 0.9094
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.7621 - val_accuracy: 0.5000 - val_loss: 1.6120
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7000 - loss: 1.0141 - val_accuracy: 0.5000 - val_loss: 1.1131
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.3000 - loss: 1.3841 - val_accuracy: 0.6667 - val_loss: 0.8096
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4000 - loss: 1.2391 - val_accuracy: 0.5000 - val_loss: 0.9000
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4000 - loss: 0.9487 - val_accuracy: 0.5000 - val_loss: 0.8776
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.7742 - val_accuracy: 0.5000 - val_loss: 1.2684
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7000 - loss: 0.8543 - val_accuracy: 0.5000 - val_loss: 1.0869
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3000 - loss: 1.0787 - val_accuracy: 0.6667 - val_loss: 0.7929
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.8096 - val_accuracy: 0.5000 - val_loss: 0.9045
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7000 - loss: 0.6437 - val_accuracy: 0.5000 - val_loss: 1.0979
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.8850 - val_accuracy: 0.6667 - val_loss: 0.7862
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4000 - loss: 0.8816 - val_accuracy: 0.6667 - val_loss: 0.7924
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4000 - loss: 0.8072 - val_accuracy: 0.5000 - val_loss: 1.0701
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7000 - loss: 0.6517 - val_accuracy: 0.5000 - val_loss: 1.0460
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.8688 - val_accuracy: 0.5000 - val_loss: 1.4183
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.9023 - val_accuracy: 0.3333 - val_loss: 0.7957
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6000 - loss: 0.6203 - val_accuracy: 0.3333 - val_loss: 0.8088
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7000 - loss: 0.6354 - val_accuracy: 0.3333 - val_loss: 0.9883
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6000 - loss: 0.9644 - val_accuracy: 0.5000 - val_loss: 1.0417
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.8694 - val_accuracy: 0.6667 - val_loss: 0.7760
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6871 - val_accuracy: 0.5000 - val_loss: 1.2602
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7000 - loss: 0.8433 - val_accuracy: 0.3333 - val_loss: 0.7839
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.7276 - val_accuracy: 0.5000 - val_loss: 0.9259
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4000 - loss: 0.7431 - val_accuracy: 0.3333 - val_loss: 0.8002
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.9270 - val_accuracy: 0.5000 - val_loss: 0.8908
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4000 - loss: 0.7968 - val_accuracy: 0.5000 - val_loss: 0.9829
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.6902 - val_accuracy: 0.5000 - val_loss: 0.9059
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7739 - val_accuracy: 0.6667 - val_loss: 0.7648
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6000 - loss: 0.6397 - val_accuracy: 0.6667 - val_loss: 0.7654
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.8705 - val_accuracy: 0.5000 - val_loss: 0.8255
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7970 - val_accuracy: 0.5000 - val_loss: 0.9013
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6000 - loss: 0.7581 - val_accuracy: 0.5000 - val_loss: 0.8152
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.7922 - val_accuracy: 0.5000 - val_loss: 0.8380
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6000 - loss: 0.8174 - val_accuracy: 0.5000 - val_loss: 0.8342
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.7265 - val_accuracy: 0.3333 - val_loss: 0.7501
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7000 - loss: 0.6695 - val_accuracy: 0.5000 - val_loss: 0.7975
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7863 - val_accuracy: 0.6667 - val_loss: 0.7462
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.7818 - val_accuracy: 0.5000 - val_loss: 0.8182
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7330 - val_accuracy: 0.5000 - val_loss: 0.8565
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6921 - val_accuracy: 0.3333 - val_loss: 0.7471
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7000 - loss: 0.6808 - val_accuracy: 0.6667 - val_loss: 0.7742
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.7212 - val_accuracy: 0.6667 - val_loss: 0.7679
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.7696 - val_accuracy: 0.6667 - val_loss: 0.7371
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7156 - val_accuracy: 0.6667 - val_loss: 0.7390
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6870 - val_accuracy: 0.5000 - val_loss: 0.7348
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.7380 - val_accuracy: 0.5000 - val_loss: 0.7913
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6000 - loss: 0.6757 - val_accuracy: 0.6667 - val_loss: 0.7414
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7020 - val_accuracy: 0.5000 - val_loss: 0.7799
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6000 - loss: 0.6598 - val_accuracy: 0.5000 - val_loss: 0.7528
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.6331 - val_accuracy: 0.6667 - val_loss: 0.7310
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.6676 - val_accuracy: 0.5000 - val_loss: 0.7952
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6000 - loss: 0.7191 - val_accuracy: 0.5000 - val_loss: 0.8300
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6000 - loss: 0.6976 - val_accuracy: 0.3333 - val_loss: 0.7454
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7000 - loss: 0.6273 - val_accuracy: 0.3333 - val_loss: 0.7311
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6486 - val_accuracy: 0.6667 - val_loss: 0.7530
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7000 - loss: 0.6800 - val_accuracy: 0.3333 - val_loss: 0.7502
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7000 - loss: 0.6298 - val_accuracy: 0.3333 - val_loss: 0.7328
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7000 - loss: 0.6742 - val_accuracy: 0.3333 - val_loss: 0.7339
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6790 - val_accuracy: 0.5000 - val_loss: 0.7959
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.4000 - loss: 0.8323 - val_accuracy: 0.3333 - val_loss: 0.7502
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4000 - loss: 0.7056 - val_accuracy: 0.3333 - val_loss: 0.7302
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6529 - val_accuracy: 0.5000 - val_loss: 0.7752
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3000 - loss: 0.8323 - val_accuracy: 0.3333 - val_loss: 0.7404
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6000 - loss: 0.6414 - val_accuracy: 0.3333 - val_loss: 0.7239
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6219 - val_accuracy: 0.3333 - val_loss: 0.7277
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8000 - loss: 0.6241 - val_accuracy: 0.3333 - val_loss: 0.7280
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7000 - loss: 0.6209 - val_accuracy: 0.3333 - val_loss: 0.7302
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6000 - loss: 0.6214 - val_accuracy: 0.3333 - val_loss: 0.7350
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7000 - loss: 0.6192 - val_accuracy: 0.3333 - val_loss: 0.7273
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6000 - loss: 0.6404 - val_accuracy: 0.6667 - val_loss: 0.7477
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6000 - loss: 0.7027 - val_accuracy: 0.6667 - val_loss: 0.7314
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.4000 - loss: 0.7368 - val_accuracy: 0.6667 - val_loss: 0.7309
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6000 - loss: 0.6811 - val_accuracy: 0.5000 - val_loss: 0.7265
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.7000 - loss: 0.6474 - val_accuracy: 0.6667 - val_loss: 0.7324
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6000 - loss: 0.6280 - val_accuracy: 0.6667 - val_loss: 0.7274
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6000 - loss: 0.6620 - val_accuracy: 0.3333 - val_loss: 0.7336
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.6000 - loss: 0.6539 - val_accuracy: 0.6667 - val_loss: 0.7304
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6000 - loss: 0.6645 - val_accuracy: 0.6667 - val_loss: 0.7685
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7000 - loss: 0.6661 - val_accuracy: 0.3333 - val_loss: 0.7383
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6000 - loss: 0.6281 - val_accuracy: 0.3333 - val_loss: 0.7372